/* Copyright (C) 2023 Harry Clark */

/* M68K OS Kernel */

/* THIS FILE PERTAINS TO THE DECLARATION OF DEFINES FOR THE CPU */
/* ALL OF THESE DEFINES ARE MEANT TO REPRESENT THE CPU ON A LOW LEVEL */

/* DOCUMENTATION USED: https://www.nxp.com/docs/en/reference-manual/MC68000UM.pdf */

#ifndef CPU_DEFINES
#define CPU_DEFINES

/* NESTED INCLUDES */

#include "common.h"
#include "sys_calls.h"

#define CPU_OBJECT

#define CPU_TLB U64

#define CPU_TLB_ENTRY (VALUE) \
static CPU_TLB_ENTRY(CPU_TLB, 4);

#define CPU_TLS (VALUE, DIVIDER) \
static CPU_TARGET_LONG_SIZE(CPU_TLB / 8);

#define CPU_VTLS 8

#define CPU_SUPERVISOR_MODE (BIT)
#define CPU_USER_MODE (BIT)

#define ADDRESS(VALUE) \
static ADDRESS(U32* ADDRESS_INDEX(ADDRESS >> 24));

#define POINTER(VALUE) \
static POINTER(U32* ADDRESS_INDEX(ADDRESS >> 16));

#define ADDRESS_BITS 64

typedef struct CPU
{
	typedef U32* DATA_REGISTER[8];
	typedef U32* ADDRESS_REGISTER[8];
	typedef U32* PROGRAM_COUNTER;
	typedef U32* STATUS_REGISTER;

	// 3 INSTANCES OF THE STACK POINTER
	// TO ACT AS A TRUTH TABLE OF SORTS
	// SEE TABLE 6-1: https://www.nxp.com/docs/en/reference-manual/MC68000UM.pdf //

	typedef U32* STACK_POINTER[3];

	typedef U32* USER_STACK_POINTER[3];

	union MMU
	{
		typedef U32* ADDRESS_REGISTER;
		typedef U32* DMA_COUNTER_LOW;
		typedef U32* DMA_COUNTER_HIGH;
		typedef U32* DMA_SOURCE_LOW;
		typedef U32* DMA_SOURCE_MID;
		typedef U32* DMA_SOURCE_HIGH; 
	};
};

#ifndef CONDITION_FLAGS
#define CONDITION_FLAGS

#define OPERAND U32 

#define FLAG_EXTEND (SIZE, VALUE) \
static EXTEND(SIZE >> 4 & 0x01);

#define FLAG_ZERO (SIZE, VALUE) \
static ZERO(SIZE >> 2 & 0x02);

#endif

VOID_FUNCTION(SET_PROGRAM_COUNTER);
VOID_FUNCTION(SET_ENV);
VOID_FUNCTION(CPU_INIT);
VOID_FUNCTION(CPU_FREE);
VOID_FUNCTION(CPU_SET_FEATURES);
VOID_FUNCTION(CPU_REGISTER_RESET);
VOID_FUNCTION(CPU_READ_REGISTERS);
VOID_FUNCTION(CPU_SET_CURRENT_CONDITION);
VOID_FUNCTION(CPU_SET_STATUS_REGISTER);
VOID_FUNCTION(CPU_SET_FPCR);

#endif
