/* COPYRIGHT (C) HARRY CLARK 2023 */

/* SEGA DREAMCAST BINARY DECOMPILER FOR IDA PRO */

/* THIS FILE PERTAINS TOWARDS THE FUNCTIONALITY SURROUNDING THE */
/* HITACHI SUPER-H 4'S OPCODES */

/* NESTED INCLUDES */

#include "common.h"

#ifndef OPCODES
#define OPCODES

#if defined(USE_OPCODES)
#define USE_OPCODES
#else
#define USE_OPCODES

/* MISC. FLOATING POINT TYPES */

#define		OPCODE_DIV0			0x0019
#define		OPCODE_RETURN		0x000B
#define		OPCODE_CLR_MAC		0x0028
#define		OPCODE_CLR_S		0x0048
#define		OPCODE_CLR_T		0x0008
#define		OPCODE_LDT_LB		0x0038
#define		OPCODE_NOP			0x0009
#define		OPCODE_RTE			0x002B
#define		OPCODE_SET_S		0x0058
#define		OPCODE_SET_T		0x0018
#define		OPCODE_SLEEP		0x001B
#define		OPCODE_FRCHG		0xFBFD
#define		OPCODE_FSCHG		0xF3FD

/* MOVE TYPES */

#define		OPCODE_MOVT			0x0029
#define		OPCODE_MOVB_DISP	0xc000		// MOV.B R0, (DISP, GBR)
#define		OPCODE_MOVW_DISP	0xc100		// MOV.W R0, (DISP, GBR)
#define		OPCODE_MOVL_DISP	0xc200		// MOV.L R0, (DISP, GBR)

#endif

#endif