/* Copyright (C) 2023 Harry Clark */

/* M68K OS Kernel */

/* THIS FILE PERTAINS TO THE FUNCTIONALITY OF THE OS' PAGING SCHEMA */
/* WHAT THIS FILE IS RESPONSIBILE FOR IS FOR TAKING INTO ACCOUNT MEMORY ALLOCATIONS */
/* AND MANAGEMENT PRINCIPLES TO ALLOCATE MEMORY ACCORDINGLY RELATIVE TO A PARTICULAR SIZE */
/* AND OR ADDRESS */

#ifndef PAGING
#define PAGING


#endif 