/* Copyright (C) 2023 Harry Clark */

/* M68K OS Kernel */

/* THIS FILE PERTAINS TO THE FUNCTIONALITY OF THE OS' SYSTEM CALLS SCHEMA */
/* DESIGNED WITH EASE OF USE IN MIND TO ALLOCATE MEMORY, INCOPERATE IO, ETC */

#ifndef SYS_CALL
#define SYS_CALL

/* NESTED INCLUDES */

#include "common.h"

#define OS_BYTE 0
#define OS_LONG 1
#define OS_WORD 2
#define OS_UNKNOWN 3

#define MAX_CONDITION_REGS 32

/* A RE-WRITE OF THE ASSEMBLY COUNTERPART OF */
/*  THE 68K VECTOR TABLE */

/* THIS IS TO HIGHLIGHT AND DECLARE CONDITIONS PERTAINING */
/* TO THE MICRO-PROCESSOR ON A LOW LEVEL SUCH AS */
/* INTERRUPTS, ERRORS, AND MEMORY MANAGEMENT VECTORS */

/* DOCUMENTATION USED: */

/* https://wiki.megadrive.org/index.php?title=68k_vector_table */

/* http://md.railgun.works/index.php?title=68k_Instruction_Reference */

#ifndef SYS_VECTOR_TABLE
#define SYS_VECTOR_TABLE

#define STACK_ADDRESS 0
#define PROGRAM_INIT 1
#define BUS_ERROR 2
#define ILLEGAL 3
#define ADDRESS_ERROR 4
#define DIV_ZERO 5
#define CHECK_INSTRUCTION 6

#endif

VOID_FUNCTION(SYS_READ);
VOID_FUNCTION(SYS_WRITE);
VOID_FUNCTION(SYS_REG_RESET);
VOID_FUNCTION(SYS_INIT);
VOID_FUNCTION(SYS_INTERRUPT);
VOID_FUNCTION(SYS_SET_STATUS);

#endif
