/* Copyright (C) 2023 Harry Clark */

/* M68K OS Kernel */

/* THIS FILE PERTAINS TO THE FUNCTIONALITY OF THE OS' SYSTEM CALLS SCHEMA */
/* DESIGNED WITH EASE OF USE IN MIND TO ALLOCATE MEMORY, INCOPERATE IO, ETC */

#ifndef SYS_CALL
#define SYS_CALL

/* NESTED INCLUDES */

#include "common.h"

#define OS_BYTE 0
#define OS_LONG 1
#define OS_WORD 2
#define OS_UNKNOWN 3

#define MAX_CONDITION_REGS 32

VOID_FUNCTION(SYS_READ);
VOID_FUNCTION(SYS_WRITE);
VOID_FUNCTION(SYS_REG_RESET);
VOID_FUNCTION(SYS_INIT);
VOID_FUNCTION(SYS_INTERRUPT);
VOID_FUNCTION(SYS_SET_STATUS);

#endif
