/* COPYRIGHT (C) HARRY CLARK 2023 */

/* SEGA DREAMCAST BINARY DECOMPILER FOR IDA PRO */

/* THIS FILE PERTAINS TOWARDS THE UNION SURROUNDING THE VECTOR TABLE */
/* WHILE THE SH4 DOESN'T HAVE A VECTOR TABLE PERSAY, IT INCLUDES A CULMINATION OF VECTOR-BASED EXCEPTIONS */
/* WHICH ARE BASICALLY THE SAME THING */

/* SEE: https://datasheet.octopart.com/D17760BP200AD-Renesas-datasheet-124679.pdf#page=217 */

#ifndef VECTORS
#define VECTORS

/* NESTED INCLUDES */

#include "common.h"

typedef struct VECTOR_TABLE
{
	union
	{
		U32 POWER_ON_RESET;
		U32 MANUAL_RESET;
		U32 H_UDI_RESET;
		U32 INSTRUCTION_TLB_HIT_EXCP;
		U32 DATA_TLB_HIT_EXCP;
		U32 USER_BREAK_INSTR_EXEC;
	};
};

#endif