/* COPYRIGHT (C) HARRY CLARK 2023 */

/* SEGA DREAMCAST BINARY DECOMPILER FOR IDA PRO */

/* THIS FILE PERTAINS TOWARDS THE UNION SURROUNDING THE VECTOR TABLE */
/* WHILE THE SH4 DOESN'T HAVE A VECTOR TABLE PERSAY, IT INCLUDES A CULMINATION OF VECTOR-BASED EXCEPTIONS */
/* WHICH ARE BASICALLY THE SAME THING */

/* SEE: https://datasheet.octopart.com/D17760BP200AD-Renesas-datasheet-124679.pdf#page=217 */

#ifndef VECTORS
#define VECTORS

/* NESTED INCLUDES */

#include "common.h"

typedef struct VECTOR_TABLE
{
	union
	{
		U32 POWER_ON_RESET;
		U32 MANUAL_RESET;
		U32 H_UDI_RESET;
		U32 INSTRUCTION_TLB_HIT_EXCP;
		U32 DATA_TLB_HIT_EXCP;
		U32 USER_BREAK_INSTR_EXEC;
		U32 INSTRUCTION_ADDR_ERROR;
		U32 INSTRUCTION_TLB_MISS_EXCP;
		U32 INSTRUCTION_TLB_PV_EXCP;
		U32 GENERAL_ILLEGAL_INSTR_EXCP;
		U32 SLOT_ILLEGAL_INSTR_EXCP;
		U32 GENERAL_FPU_DISABLE_EXCP;
		U32 SLOT_FPU_DISABLE_EXCP;
		U32 DATA_ADDRESS_ERROR_READ;
		U32 DATA_ADDRESS_ERROR_WRITE;
		U32 DATA_TLB_MISS_EXCP_READ;
		U32 DATA_TLB_MISS_EXCP_WRITE;
		U32 DATA_TLB_PV_EXCP_READ;
		U32 DATA_TLB_PV_EXCP_WRITE;
		U32 FPU_EXCP;
		U32 INITIAL_PAGE_WRITE_EXCP;
		U32 UNCONDITIONAL_TRAP;
		U32 USER_BREAK_INSTR_EXCP;
	};
};

/* CONCATENATE VECTOR BASED TYPES IF NECESSARY */

#define			VECTOR_FUNCTION(VALUE)				 \
static VECTOR_TABLE* TYPE ## VALUE(U8 EXCEPTION_CODE);

#define			VECTOR_OFFSET(VALUE)			   \
static VECTOR_TABLE* TYPEE ## VALUE(U8 OFFSET_CODE);

#endif
