/* COPYRIGHT (C) HARRY CLARK 2023 */

/* SEGA DREAMCAST BINARY DECOMPILER FOR IDA PRO */

/* THIS FILE PERTAINS TOWARDS THE MAIN FUNCTIONALITY */
/* SURROUNDING THE VECTOR TABLE */

/* NESTED INCLUDES */

#include "disasm.h"

static VECTOR_TABLE* VECTOR;
static HEADER* BINARY_HEADER;

/* INITIALISES THE PROVIDED BINARY BY USING THE PRE-DEFINED */
/* DIRECTIVES FROM THE IDA API TO LOAD AND PARSE CONTENTS */

static U32 idaapi INIT_BINARY(qstring* FILE_FORMAT,
							  const char* FILENAME,
							  qstring* PROCESSOR,
							  linput_t* LOADER)
{
	// PARSE THE INPUT SOURCE RELATIVE TO THE SIZE OF THE CORRESPONDENCES

	if (qlread(LOADER, &VECTOR, sizeof(VECTOR)) != sizeof(VECTOR)) return 0;
	if (qlread(LOADER, &BINARY_HEADER, sizeof(BINARY_HEADER)) != sizeof(BINARY_HEADER)) return 0;

	// USES IDA'S VERSION OF "sprintf" TO CONCATENATE A STRING

	FILE_FORMAT->sprnt("%s", "SEGA DREAMCAST BINARY");
	return 1;
}
