/* COPYRIGHT (C) HARRY CLARK 2023 */

/* SEGA DREAMCAST BINARY DECOMPILER FOR IDA PRO */

/* THIS FILE PERTAINS TOWARDS THE MAIN FUNCTIONALITY */
/* SURROUNDING THE VECTOR TABLE */

/* NESTED INCLUDES */

#include "disasm.h"

static VECTOR_TABLE* VECTOR;

/* INITIALISES THE PROVIDE BINARY BY USING */

static U32 idaapi INIT_BINARY(qstring* FILE_NAME,
							  qstring* PROCESSOR,
							  linput_t* LOADER)
{
	qlread(LOADER, &VECTOR, sizeof(VECTOR));
	return 0;
}